### ISSUE TITLE
load_from_disk() conflicts on desktop vs venv

### ISSUE THREAD

**Issue by timseymore** [timseymore/todo-tracker#22]
using new todo.py in desktop crashes on ls command unless move data.obj to todo-tracker dir, which causes loss of persistent data

**Comment by timseymore** [comment]
>>> ls

ToDo Tracker
  Recipe Page
Traceback (most recent call last):
  File "todo.py", line 345, in <module>
    ToDoTracker().main()
  File "todo.py", line 205, in main
    current_task = self.handle_input(choice, current_task)
  File "todo.py", line 235, in handle_input
    current.display("")
  File "todo.py", line 165, in display
    sub.display(indent_space + "  ")
  File "todo.py", line 165, in display
    sub.display(indent_space + "  ")
  File "todo.py", line 102, in display
    print(indent_space + self.get_description())
  File "todo.py", line 87, in get_description
    if not self.date == "":
AttributeError: 'ToDo' object has no attribute 'date'

**Comment by timseymore** [comment]
Determined this issue is caused by using data.obj file containing old version save ; no date or location fields exist in old version, causing AttributeError to be thrown.
